from setuptools import setup, find_packages

setup(
    name='abyss',
    version='0.1',
    author='Shawn Lawyer',
    author_email='shawnlawyer@gmail.com',
    description='My Python app',
    url='https://github.com/shawnlawyer/abyss',
    packages=find_packages(),
    install_requires=[
        'absl-py==1.4.0',
        'astunparse==1.6.3',
        'blessed==1.20.0',
        'cachetools==5.3.0',
        'certifi==2022.12.7',
        'charset-normalizer==3.1.0',
        'click==8.1.3',
        'filelock==3.12.0',
        'flatbuffers==23.3.3',
        'fsspec==2023.4.0',
        'gast==0.4.0',
        'google-auth==2.17.3',
        'google-auth-oauthlib==1.0.0',
        'google-pasta==0.2.0',
        'grpcio==1.54.0',
        'gviz-api==1.10.0',
        'h5py==3.8.0',
        'huggingface-hub==0.14.1',
        'idna==3.4',
        'jax==0.4.8',
        'joblib==1.2.0',
        'keras==2.12.0',
        'keras-tuner==1.3.5',
        'kt-legacy==1.0.5',
        'libclang==16.0.0',
        'Markdown==3.4.3',
        'MarkupSafe==2.1.2',
        'ml-dtypes==0.1.0',
        'numpy==1.23.5',
        'nvidia-cublas-cu11==11.11.3.6',
        'nvidia-cudnn-cu11==8.6.0.163',
        'oauthlib==3.2.2',
        'opt-einsum==3.3.0',
        'packaging==23.1',
        'protobuf==4.22.3',
        'pyasn1==0.5.0',
        'pyasn1-modules==0.3.0',
        'pygame==2.3.0',
        'PyYAML==6.0',
        'regex==2023.3.23',
        'requests==2.28.2',
        'requests-oauthlib==1.3.1',
        'rsa==4.9',
        'scikit-learn==1.2.2',
        'scipy==1.10.1',
        'silence-tensorflow==1.2.1',
        'six==1.16.0',
        'support-developer==1.0.5',
        'tensorboard==2.12.2',
        'tensorboard-data-server==0.7.0',
        'tensorboard-plugin-profile==2.11.2',
        'tensorboard-plugin-wit==1.8.1',
        'tensorflow==2.12.0',
        'tensorflow-estimator==2.12.0',
        'tensorflow-io-gcs-filesystem==0.32.0',
        'termcolor==2.2.0',
        'threadpoolctl==3.1.0',
        'tokenizers==0.13.3',
        'tqdm==4.65.0',
        'transformers==4.28.1',
        'typing_extensions==4.5.0',
        'urllib3==1.26.15',
        'wcwidth==0.2.6',
        'Werkzeug==2.2.3',
        'wrapt==1.14.1'
    ],
    entry_points={
        'console_scripts': [
            'abyss=app.main:main',
        ],
    },
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3.9',
    ],
    python_requires='>=3.9',
)

